CREATE TABLE orders (
    id BIGINT generated by default as identity primary key,
    created_at timestamp with time zone NOT NULL,
    total_amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL
);