CREATE TABLE order_items (
    id BIGINT generated by default as identity primary key,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC(15, 2) NOT NULL
);