CREATE TABLE verification_tokens (
     id BIGINT generated by default as identity primary key,
     user_id BIGINT NOT NULL,
     token VARCHAR(255) NOT NULL UNIQUE,
     expiry_date TIMESTAMP NOT NULL,
     CONSTRAINT fk_verification_user
         FOREIGN KEY(user_id)
             REFERENCES users(id)
             ON DELETE CASCADE
);