CREATE TABLE payments (
    id bigint generated by default as identity primary key,
    order_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at timestamp with time zone NOT NULL
);