server:
  port: 8082


spring:
  liquibase:
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/inventorydb
    username: auth_user
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:29092
    topics:
      product-created: product-created-topic
    group-id: inventory-group
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "com.example.platform.dto"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
