server:
  port: 8082


spring:
  liquibase:
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/inventorydb
    username: auth_user
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true